languages = {
    "Albania": "Albanian",
    "Andorra": "Catalan",
    "Austria": "German",
    "Belarus": "Russian",
    "Belgium": "Dutch",
    "Bosnia and Herzegovina": "Bosnian",
    "Bulgaria": "Bulgarian",
    "Croatia": "Croatian",
    "Cyprus": "Greek",
    "Czech Republic": "Czech",
    "Denmark": "Danish",
    "Estonia": "Estonian",
    "Finland": "Finnish",
    "France": "French",
    "Germany": "German",
    "Greece": "Greek",
    "Hungary": "Hungarian",
    "Iceland": "Icelandic",
    "Ireland": "English",
    "Italy": "Italian",
    "Kosovo": "Albanian",
    "Latvia": "Latvian",
    "Lithuania": "Lithuanian",
    "Luxembourg": "Luxembourgish",
    "Malta": "Maltese",
    "Moldova": "Romanian",
    "Monaco": "French",
    "Montenegro": "Montenegrin",
    "Netherlands": "Dutch",
    "North Macedonia": "Macedonian",
    "Norway": "Norwegian",
    "Poland": "Polish",
    "Portugal": "Portuguese",
    "Romania": "Romanian",
    "Russia": "Russian",
    "San Marino": "Italian",
    "Serbia": "Serbian",
    "Slovakia": "Slovak",
    "Slovenia": "Slovene",
    "Spain": "Spanish",
    "Sweden": "Swedish",
    "Switzerland": "German",
    "Ukraine": "Ukrainian",
    "United Kingdom": "English",
    "UК": "English",
    "England": "English",
    "Vatican City": "Italian",
    "Antigua and Barbuda": "English",
    "Argentina": "Spanish",
    "Bahamas": "English",
    "Barbados": "English",
    "Belize": "English",
    "Bolivia": "Spanish",
    "Brazil": "Portuguese",
    "Canada": "English",
    "Chile": "Spanish",
    "Colombia": "Spanish",
    "Costa Rica": "Spanish",
    "Cuba": "Spanish",
    "Dominica": "English",
    "Dominican Republic": "Spanish",
    "Ecuador": "Spanish",
    "El Salvador": "Spanish",
    "Grenada": "English",
    "Guatemala": "Spanish",
    "Guyana": "English",
    "Haiti": "Haitian Creole",
    "Honduras": "Spanish",
    "Jamaica": "English",
    "Mexico": "Spanish",
    "Nicaragua": "Spanish",
    "Panama": "Spanish",
    "Paraguay": "Spanish",
    "Peru": "Spanish",
    "Saint Kitts and Nevis": "English",
    "Saint Lucia": "English",
    "Saint Vincent and the Grenadines": "English",
    "Suriname": "Dutch",
    "Trinidad and Tobago": "English",
    "United States": "English",
    "USA": "English",
    "Uruguay": "Spanish",
    "Venezuela": "Spanish",
    "Afghanistan": "Dari",
    "Armenia": "Armenian",
    "Azerbaijan": "Azerbaijani",
    "Bahrain": "Arabic",
    "Bangladesh": "Bengali",
    "Bhutan": "Dzongkha",
    "Brunei": "Malay",
    "Cambodia": "Khmer",
    "China": "Mandarin Chinese",
    "Georgia": "Georgian",
    "India": "Hindi",
    "Indonesia": "Indonesian",
    "Iran": "Persian",
    "Iraq": "Arabic",
    "Israel": "Hebrew",
    "Japan": "Japanese",
    "Jordan": "Arabic",
    "Kazakhstan": "Kazakh",
    "Kuwait": "Arabic",
    "Kyrgyzstan": "Kyrgyz",
    "Laos": "Lao",
    "Lebanon": "Arabic",
    "Malaysia": "Malay",
    "Maldives": "Dhivehi",
    "Mongolia": "Mongolian",
    "Myanmar": "Burmese",
    "Nepal": "Nepali",
    "North Korea": "Korean",
    "Oman": "Arabic",
    "Pakistan": "Urdu",
    "Palestine": "Arabic",
    "Philippines": "Filipino",
    "Qatar": "Arabic",
    "Saudi Arabia": "Arabic",
    "Singapore": "Mandarin Chinese",
    "South Korea": "Korean",
    "Sri Lanka": "Sinhala",
    "Syria": "Arabic",
    "Taiwan": "Mandarin Chinese",
    "Tajikistan": "Tajik",
    "Thailand": "Thai",
    "Timor-Leste": "Tetum",
    "Turkey": "Turkish",
    "Turkmenistan": "Turkmen",
    "United Arab Emirates": "Arabic",
    "Uzbekistan": "Uzbek",
    "Vietnam": "Vietnamese",
    "Yemen": "Arabic"
}
